## This file loads, computes, and presents the results of all of our AU intensity estimation and AU detection methods from Table 2 to Table 6.

In [1]:
import numpy as np
import pickle as pkl
import os
from collections import defaultdict
from IPython.display import display
from config.datasets import *
from config.models import *
from lib.stats import *

In [2]:
# Infomation of all tasks/methods to load
infos = [{"task": "DISFA_AU_intensity_estimation_threefold", "dataset": "DISFA", "n_folds": 3, "AUs": DISFA_AUS_IE, "label_type": "intensity", "model": "IR50", "sub_idx": -2},
         {"task": "DISFA_AU_intensity_estimation_threefold", "dataset": "DISFA", "n_folds": 3, "AUs": DISFA_AUS_IE, "label_type": "intensity", "model": "CSN-IR50-stage4", "sub_idx": -2},
         {"task": "DISFAPlus_AU_intensity_estimation_ninefold", "dataset": "DISFA+", "n_folds": 9, "AUs": DISFAPLUS_AUS, "label_type": "intensity", "model": "IR50", "sub_idx": -3},
         {"task": "DISFAPlus_AU_intensity_estimation_ninefold", "dataset": "DISFA+", "n_folds": 9, "AUs": DISFAPLUS_AUS, "label_type": "intensity", "model": "CSN-IR50-stage4", "sub_idx": -3},
         {"task": "UNBCMcMaster_AU_intensity_estimation_fivefold", "dataset": "UNBCMcMaster", "n_folds": 5, "AUs": UNBCMCMASTER_AUS_IE, "label_type": "intensity", "model": "IR50", "sub_idx": -3},
         {"task": "UNBCMcMaster_AU_intensity_estimation_fivefold", "dataset": "UNBCMcMaster", "n_folds": 5, "AUs": UNBCMCMASTER_AUS_IE, "label_type": "intensity", "model": "CSN-IR50-stage4", "sub_idx": -3},
         {"task": "DISFA_AU_detection_threefold", "dataset": "DISFA", "n_folds": 3, "AUs": DISFA_AUS_D, "label_type": "occurrence", "model": "IR50", "sub_idx": -2},
         {"task": "DISFA_AU_detection_threefold", "dataset": "DISFA", "n_folds": 3, "AUs": DISFA_AUS_D, "label_type": "occurrence", "model": "CSN-IR50-stage4", "sub_idx": -2},
         {"task": "DISFAPlus_AU_detection_ninefold", "dataset": "DISFA+", "n_folds": 9, "AUs": DISFAPLUS_AUS, "label_type": "occurrence", "model": "IR50", "sub_idx": -3},
         {"task": "DISFAPlus_AU_detection_ninefold", "dataset": "DISFA+", "n_folds": 9, "AUs": DISFAPLUS_AUS, "label_type": "occurrence", "model": "CSN-IR50-stage4", "sub_idx": -3},
         {"task": "UNBCMcMaster_AU_detection_fivefold", "dataset": "UNBCMcMaster", "n_folds": 5, "AUs": UNBCMCMASTER_AUS_D, "label_type": "occurrence", "model": "IR50", "sub_idx": -3},
         {"task": "UNBCMcMaster_AU_detection_fivefold", "dataset": "UNBCMcMaster", "n_folds": 5, "AUs": UNBCMCMASTER_AUS_D, "label_type": "occurrence", "model": "CSN-IR50-stage4", "sub_idx": -3},
         {"task": "DISFA_AU_intensity_estimation_threefold", "dataset": "DISFA", "n_folds": 3, "AUs": DISFA_AUS_IE, "label_type": "intensity", "model": "CSN-IR50-stage1", "sub_idx": -2},
         {"task": "DISFA_AU_intensity_estimation_threefold", "dataset": "DISFA", "n_folds": 3, "AUs": DISFA_AUS_IE, "label_type": "intensity", "model": "CSN-IR50-stage2", "sub_idx": -2},
         {"task": "DISFA_AU_intensity_estimation_threefold", "dataset": "DISFA", "n_folds": 3, "AUs": DISFA_AUS_IE, "label_type": "intensity", "model": "CSN-IR50-stage3", "sub_idx": -2},
         {"task": "DISFA_AU_intensity_estimation_threefold", "dataset": "DISFA", "n_folds": 3, "AUs": DISFA_AUS_IE, "label_type": "intensity", "model": "CSN-IR50-fc", "sub_idx": -2},
         {"task": "DISFA_AU_intensity_estimation_threefold", "dataset": "DISFA", "n_folds": 3, "AUs": DISFA_AUS_IE, "label_type": "intensity", "model": "CSN-IR50-output", "sub_idx": -2},
         {"task": "DISFA_AU_detection_threefold", "dataset": "DISFA", "n_folds": 3, "AUs": DISFA_AUS_D, "label_type": "occurrence", "model": "CSN-IR50-stage1", "sub_idx": -2},
         {"task": "DISFA_AU_detection_threefold", "dataset": "DISFA", "n_folds": 3, "AUs": DISFA_AUS_D, "label_type": "occurrence", "model": "CSN-IR50-stage2", "sub_idx": -2},
         {"task": "DISFA_AU_detection_threefold", "dataset": "DISFA", "n_folds": 3, "AUs": DISFA_AUS_D, "label_type": "occurrence", "model": "CSN-IR50-stage3", "sub_idx": -2},
         {"task": "DISFA_AU_detection_threefold", "dataset": "DISFA", "n_folds": 3, "AUs": DISFA_AUS_D, "label_type": "occurrence", "model": "CSN-IR50-fc", "sub_idx": -2},
         {"task": "DISFA_AU_detection_threefold", "dataset": "DISFA", "n_folds": 3, "AUs": DISFA_AUS_D, "label_type": "occurrence", "model": "CSN-IR50-output", "sub_idx": -2}]

In [3]:
for info in infos:
    # Load the data
    all_image_paths = []
    all_pred_labels = np.empty([0, len(info["AUs"])])
    all_true_labels = np.empty([0, len(info["AUs"])])

    for fold in range(1, info["n_folds"]+1):
        path = os.path.join("results", info["task"], info["model"], "results", f"fold-{fold}", f"val_results_epoch{N_EPOCHS}.pkl")
        with open(path, "rb") as f:
            D = pkl.load(f)
            image_paths = [path_pair.split(' ')[-1] for path_pair in D['image_paths']]
            if info["label_type"] == "intensity":
                pred_labels = D['pred_labels_regression']
            elif info["label_type"] == "occurrence":
                pred_labels = D['pred_labels']
            true_labels = D['true_labels']
            all_image_paths.extend(image_paths)
            all_pred_labels = np.concatenate([all_pred_labels, pred_labels])
            all_true_labels = np.concatenate([all_true_labels, true_labels])
    
    # Find out the indices for each participant in the results
    subject_indices = defaultdict(list)
    for index, path in enumerate(all_image_paths):
        subject_indices[path.split('/')[info["sub_idx"]]].append(index)
    sub_IDs = list(subject_indices.keys())

    # Compute the evaluation metrics from the results
    if info["label_type"] == "intensity":
        df = compute_results_for_intensity_estimation(info, all_pred_labels, all_true_labels, subject_indices, sub_IDs)
    elif info["label_type"] == "occurrence":
        df = compute_results_for_occurrence_detection(info, all_pred_labels, all_true_labels, subject_indices)

    # Display the results
    print(f"{info["task"]}    {info["model"]}")
    display(df)

    # For IR50, also compute and present the results for one-frame calibration with baseline subtraction
    if info["model"] == "IR50":
        if info["dataset"] == "DISFA":
            cam_angles = ['Left' if 'Left' in p else 'Right' if 'Right' in p else None for p in all_image_paths]
            subjects = [p.split('/')[info["sub_idx"]] for p in all_image_paths]
            combs = list(zip(cam_angles, subjects))
            combs_unique = list(set(combs))
            baseline_idx_dict = {comb: [(comb[0] in path) and (comb[1] in path) and (f"{DISFA_BASELINE_FRAMES[comb[1]]}.jpg" in path.split('/')) for path in all_image_paths].index(True) for comb in combs_unique}
            baseline_idx = [baseline_idx_dict[comb] for comb in combs]
            baselined_all_pred_labels = all_pred_labels - all_pred_labels[baseline_idx,:]
        elif info["dataset"] == "DISFA+":
            subjects = [p.split('/')[info["sub_idx"]] for p in all_image_paths]
            baseline_idx_dict = {sub: [(sub in path) and (DISFAPLUS_BASELINE_FRAMES[sub] in path) for path in all_image_paths].index(True) for sub in list(subject_indices.keys())}
            baseline_idx = [baseline_idx_dict[sub] for sub in subjects]
            baselined_all_pred_labels = all_pred_labels - all_pred_labels[baseline_idx,:]
        elif info["dataset"] == "UNBCMcMaster":
            subjects = [p.split('/')[info["sub_idx"]] for p in all_image_paths]
            baseline_idx_dict = {sub: [(sub in path) and (UNBCMCMASTER_BASELINE_FRAMES[sub] in path) for path in all_image_paths].index(True) for sub in list(subject_indices.keys())}
            baseline_idx = [baseline_idx_dict[sub] for sub in subjects]
            baselined_all_pred_labels = all_pred_labels - all_pred_labels[baseline_idx,:]

        if info["label_type"] == "intensity":
            df = compute_results_for_intensity_estimation(info, baselined_all_pred_labels, all_true_labels, subject_indices, sub_IDs)
        else:
            df = compute_results_for_occurrence_detection(info, baselined_all_pred_labels, all_true_labels, subject_indices)

        print(f"{info["task"]}    {info["model"]}    One-Frame Calibration with Baseline Subtraction")
        display(df)

PCCs: .53 & .45 & .75 & .62 & .58 & .60 & .84 & .46 & .47 & .25 & .94 & .66 & .60
acrossICCs: .53 & .45 & .75 & .62 & .55 & .57 & .84 & .42 & .47 & .24 & .93 & .65 & .59
withinICCs: .40 & .35 & .66 & .38 & .54 & .46 & .83 & .27 & .45 & .26 & .93 & .57 & .51
MAEs: .37 & .39 & .44 & .11 & .35 & .21 & .34 & .20 & .39 & .21 & .32 & .42 & .31
MSEs: .47 & .57 & .58 & .05 & .37 & .21 & .28 & .13 & .41 & .18 & .21 & .38 & .32
DISFA_AU_intensity_estimation_threefold    IR50

,PCC,"across-participant ICC(3,1)","within-participant ICC(3,1)",MAE,MSE
AU,,,,,
1,0.53,0.53,0.40,0.37,0.47
2,0.45,0.45,0.35,0.39,0.57
4,0.75,0.75,0.66,0.44,0.58
5,0.62,0.62,0.38,0.11,0.05
6,0.58,0.55,0.54,0.35,0.37
9,0.60,0.57,0.46,0.21,0.21
12,0.84,0.84,0.83,0.34,0.28
15,0.46,0.42,0.27,0.20,0.13
17,0.47,0.47,0.45,0.39,0.41
20,0.25,0.24,0.26,0.21,0.18
25,0.94,0.93,0.93,0.32,0.21
26,0.66,0.65,0.57,0.42,0.38
average,0.60,0.59,0.51,0.31,0.32

PCCs: .63 & .51 & .76 & .56 & .64 & .63 & .83 & .45 & .45 & .20 & .94 & .69 & .61
acrossICCs: .62 & .51 & .75 & .56 & .60 & .59 & .82 & .39 & .45 & .20 & .93 & .68 & .59
withinICCs: .40 & .35 & .66 & .38 & .54 & .46 & .83 & .27 & .44 & .26 & .93 & .57 & .51
MAEs: .31 & .36 & .41 & .14 & .33 & .20 & .39 & .18 & .37 & .29 & .33 & .38 & .31
MSEs: .37 & .49 & .53 & .07 & .32 & .20 & .33 & .13 & .37 & .31 & .25 & .33 & .31
DISFA_AU_intensity_estimation_threefold    IR50    One-Frame Calibration with Baseline Subtraction

,PCC,"across-participant ICC(3,1)","within-participant ICC(3,1)",MAE,MSE
AU,,,,,
1,0.63,0.62,0.40,0.31,0.37
2,0.51,0.51,0.35,0.36,0.49
4,0.76,0.75,0.66,0.41,0.53
5,0.56,0.56,0.38,0.14,0.07
6,0.64,0.60,0.54,0.33,0.32
9,0.63,0.59,0.46,0.20,0.20
12,0.83,0.82,0.83,0.39,0.33
15,0.45,0.39,0.27,0.18,0.13
17,0.45,0.45,0.44,0.37,0.37
20,0.20,0.20,0.26,0.29,0.31
25,0.94,0.93,0.93,0.33,0.25
26,0.69,0.68,0.57,0.38,0.33
average,0.61,0.59,0.51,0.31,0.31

PCCs: .79 & .75 & .81 & .72 & .70 & .63 & .86 & .36 & .57 & .43 & .94 & .79 & .70
acrossICCs: .75 & .70 & .80 & .72 & .67 & .61 & .85 & .33 & .52 & .37 & .94 & .77 & .67
withinICCs: .46 & .43 & .70 & .39 & .57 & .48 & .85 & .23 & .44 & .27 & .93 & .66 & .53
MAEs: .19 & .16 & .38 & .08 & .26 & .19 & .31 & .17 & .22 & .13 & .27 & .27 & .22
MSEs: .19 & .19 & .48 & .04 & .27 & .20 & .26 & .15 & .22 & .13 & .20 & .21 & .21
DISFA_AU_intensity_estimation_threefold    CSN-IR50-stage4

,PCC,"across-participant ICC(3,1)","within-participant ICC(3,1)",MAE,MSE
AU,,,,,
1,0.79,0.75,0.46,0.19,0.19
2,0.75,0.70,0.43,0.16,0.19
4,0.81,0.80,0.70,0.38,0.48
5,0.72,0.72,0.39,0.08,0.04
6,0.70,0.67,0.57,0.26,0.27
9,0.63,0.61,0.48,0.19,0.20
12,0.86,0.85,0.85,0.31,0.26
15,0.36,0.33,0.23,0.17,0.15
17,0.57,0.52,0.44,0.22,0.22
20,0.43,0.37,0.27,0.13,0.13
25,0.94,0.94,0.93,0.27,0.20
26,0.79,0.77,0.66,0.27,0.21
average,0.70,0.67,0.53,0.22,0.21

PCCs: .81 & .76 & .89 & .79 & .90 & .89 & .91 & .82 & .74 & .60 & .92 & .83 & .82
acrossICCs: .81 & .76 & .88 & .79 & .87 & .87 & .90 & .80 & .73 & .60 & .91 & .82 & .81
withinICCs: .84 & .85 & .89 & .80 & .87 & .89 & .90 & .79 & .80 & .61 & .94 & .85 & .84
MAEs: .48 & .51 & .40 & .44 & .29 & .24 & .32 & .24 & .42 & .30 & .40 & .39 & .37
MSEs: .55 & .72 & .34 & .58 & .24 & .18 & .25 & .16 & .42 & .23 & .38 & .34 & .37
DISFAPlus_AU_intensity_estimation_ninefold    IR50

,PCC,"across-participant ICC(3,1)","within-participant ICC(3,1)",MAE,MSE
AU,,,,,
1,0.81,0.81,0.84,0.48,0.55
2,0.76,0.76,0.85,0.51,0.72
4,0.89,0.88,0.89,0.40,0.34
5,0.79,0.79,0.80,0.44,0.58
6,0.90,0.87,0.87,0.29,0.24
9,0.89,0.87,0.89,0.24,0.18
12,0.91,0.90,0.90,0.32,0.25
15,0.82,0.80,0.79,0.24,0.16
17,0.74,0.73,0.80,0.42,0.42
20,0.60,0.60,0.61,0.30,0.23
25,0.92,0.91,0.94,0.40,0.38
26,0.83,0.82,0.85,0.39,0.34
average,0.82,0.81,0.84,0.37,0.37

PCCs: .84 & .86 & .89 & .84 & .90 & .91 & .91 & .83 & .76 & .61 & .95 & .87 & .85
acrossICCs: .83 & .85 & .87 & .83 & .88 & .89 & .90 & .81 & .75 & .60 & .94 & .85 & .83
withinICCs: .84 & .85 & .89 & .80 & .87 & .89 & .90 & .79 & .80 & .61 & .94 & .85 & .84
MAEs: .49 & .42 & .35 & .42 & .26 & .21 & .29 & .21 & .30 & .26 & .29 & .29 & .32
MSEs: .56 & .43 & .34 & .43 & .23 & .15 & .24 & .15 & .31 & .21 & .24 & .27 & .30
DISFAPlus_AU_intensity_estimation_ninefold    IR50    One-Frame Calibration with Baseline Subtraction

,PCC,"across-participant ICC(3,1)","within-participant ICC(3,1)",MAE,MSE
AU,,,,,
1,0.84,0.83,0.84,0.49,0.56
2,0.86,0.85,0.85,0.42,0.43
4,0.89,0.87,0.89,0.35,0.34
5,0.84,0.83,0.80,0.42,0.43
6,0.90,0.88,0.87,0.26,0.23
9,0.91,0.89,0.89,0.21,0.15
12,0.91,0.90,0.90,0.29,0.24
15,0.83,0.81,0.79,0.21,0.15
17,0.76,0.75,0.80,0.30,0.31
20,0.61,0.60,0.61,0.26,0.21
25,0.95,0.94,0.94,0.29,0.24
26,0.87,0.85,0.85,0.29,0.27
average,0.85,0.83,0.84,0.32,0.30

PCCs: .91 & .93 & .90 & .90 & .91 & .92 & .92 & .84 & .83 & .61 & .94 & .89 & .88
acrossICCs: .90 & .92 & .88 & .89 & .90 & .91 & .92 & .81 & .80 & .57 & .94 & .88 & .86
withinICCs: .89 & .91 & .88 & .86 & .90 & .91 & .92 & .76 & .82 & .57 & .94 & .88 & .85
MAEs: .26 & .22 & .29 & .29 & .23 & .18 & .24 & .17 & .21 & .21 & .24 & .24 & .23
MSEs: .25 & .18 & .30 & .27 & .20 & .13 & .20 & .14 & .22 & .20 & .23 & .23 & .21
DISFAPlus_AU_intensity_estimation_ninefold    CSN-IR50-stage4

,PCC,"across-participant ICC(3,1)","within-participant ICC(3,1)",MAE,MSE
AU,,,,,
1,0.91,0.90,0.89,0.26,0.25
2,0.93,0.92,0.91,0.22,0.18
4,0.90,0.88,0.88,0.29,0.30
5,0.90,0.89,0.86,0.29,0.27
6,0.91,0.90,0.90,0.23,0.20
9,0.92,0.91,0.91,0.18,0.13
12,0.92,0.92,0.92,0.24,0.20
15,0.84,0.81,0.76,0.17,0.14
17,0.83,0.80,0.82,0.21,0.22
20,0.61,0.57,0.57,0.21,0.20
25,0.94,0.94,0.94,0.24,0.23
26,0.89,0.88,0.88,0.24,0.23
average,0.88,0.86,0.85,0.23,0.21

PCCs: .20 & .51 & .33 & .32 & .32 & .55 & .17 & .29 & .10 & .31
acrossICCs: .19 & .51 & .30 & .32 & .29 & .55 & .17 & .28 & .09 & .30
withinICCs: .11 & .53 & .24 & .18 & .05 & .50 & .07 & .22 & .11 & .22
MAEs: .21 & .48 & .34 & .12 & .11 & .48 & .19 & .33 & .34 & .29
MSEs: .17 & .68 & .36 & .08 & .07 & .70 & .10 & .36 & .40 & .32
UNBCMcMaster_AU_intensity_estimation_fivefold    IR50

,PCC,"across-participant ICC(3,1)","within-participant ICC(3,1)",MAE,MSE
AU,,,,,
4,0.20,0.19,0.11,0.21,0.17
6,0.51,0.51,0.53,0.48,0.68
7,0.33,0.30,0.24,0.34,0.36
9,0.32,0.32,0.18,0.12,0.08
10,0.32,0.29,0.05,0.11,0.07
12,0.55,0.55,0.50,0.48,0.70
20,0.17,0.17,0.07,0.19,0.10
25,0.29,0.28,0.22,0.33,0.36
26,0.10,0.09,0.11,0.34,0.40
average,0.31,0.30,0.22,0.29,0.32

PCCs: .28 & .60 & .43 & .33 & .36 & .63 & .18 & .33 & .17 & .37
acrossICCs: .24 & .59 & .37 & .32 & .33 & .62 & .17 & .31 & .15 & .34
withinICCs: .11 & .53 & .24 & .18 & .05 & .50 & .07 & .22 & .11 & .22
MAEs: .16 & .37 & .28 & .12 & .10 & .40 & .13 & .26 & .28 & .23
MSEs: .14 & .46 & .30 & .08 & .06 & .48 & .08 & .30 & .32 & .25
UNBCMcMaster_AU_intensity_estimation_fivefold    IR50    One-Frame Calibration with Baseline Subtraction

,PCC,"across-participant ICC(3,1)","within-participant ICC(3,1)",MAE,MSE
AU,,,,,
4,0.28,0.24,0.11,0.16,0.14
6,0.60,0.59,0.53,0.37,0.46
7,0.43,0.37,0.24,0.28,0.30
9,0.33,0.32,0.18,0.12,0.08
10,0.36,0.33,0.05,0.10,0.06
12,0.63,0.62,0.50,0.40,0.48
20,0.18,0.17,0.07,0.13,0.08
25,0.33,0.31,0.22,0.26,0.30
26,0.17,0.15,0.11,0.28,0.32
average,0.37,0.34,0.22,0.23,0.25

PCCs: .50 & .68 & .54 & .49 & .57 & .72 & .14 & .39 & .32 & .48
acrossICCs: .41 & .67 & .49 & .47 & .49 & .70 & .14 & .39 & .29 & .45
withinICCs: .18 & .56 & .26 & .20 & .08 & .56 & .07 & .27 & .13 & .26
MAEs: .12 & .28 & .27 & .08 & .08 & .37 & .11 & .26 & .22 & .20
MSEs: .11 & .36 & .26 & .06 & .04 & .38 & .08 & .31 & .29 & .21
UNBCMcMaster_AU_intensity_estimation_fivefold    CSN-IR50-stage4

,PCC,"across-participant ICC(3,1)","within-participant ICC(3,1)",MAE,MSE
AU,,,,,
4,0.50,0.41,0.18,0.12,0.11
6,0.68,0.67,0.56,0.28,0.36
7,0.54,0.49,0.26,0.27,0.26
9,0.49,0.47,0.20,0.08,0.06
10,0.57,0.49,0.08,0.08,0.04
12,0.72,0.70,0.56,0.37,0.38
20,0.14,0.14,0.07,0.11,0.08
25,0.39,0.39,0.27,0.26,0.31
26,0.32,0.29,0.13,0.22,0.29
average,0.48,0.45,0.26,0.20,0.21

accs: 87.1 & 87.1 & 86.8 & 89.5 & 95.5 & 93.2 & 95.3 & 89.6 & 90.5
F1_scores: 35.4 & 33.0 & 64.4 & 48.6 & 51.8 & 77.1 & 91.9 & 58.1 & 57.5
precisions: 23.6 & 21.2 & 54.8 & 39.7 & 46.8 & 67.9 & 89.0 & 45.0 & 48.5
recalls: 71.0 & 73.9 & 78.0 & 62.6 & 58.1 & 89.2 & 94.9 & 81.8 & 76.2
DISFA_AU_detection_threefold    IR50

         Accuracy  F1 score  Precision  Recall
AU
1            87.1      35.4       23.6    71.0
2            87.1      33.0       21.2    73.9
4            86.8      64.4       54.8    78.0
6            89.5      48.6       39.7    62.6
9            95.5      51.8       46.8    58.1
12           93.2      77.1       67.9    89.2
25           95.3      91.9       89.0    94.9
26           89.6      58.1       45.0    81.8
average      90.5      57.5       48.5    76.2

accs: 51.1 & 62.4 & 44.0 & 39.9 & 34.1 & 57.3 & 63.9 & 53.2 & 50.7
F1_scores: 16.5 & 17.3 & 35.1 & 20.5 & 11.1 & 37.5 & 60.5 & 25.6 & 28.0
precisions: 9.0 & 9.6 & 21.3 & 11.4 & 5.9 & 23.1 & 43.4 & 14.9 & 17.3
recalls: 96.8 & 91.5 & 99.5 & 98.0 & 97.9 & 99.4 & 99.8 & 91.6 & 96.8
DISFA_AU_detection_threefold    IR50    One-Frame Calibration with Baseline Subtraction

         Accuracy  F1 score  Precision  Recall
AU
1            51.1      16.5        9.0    96.8
2            62.4      17.3        9.6    91.5
4            44.0      35.1       21.3    99.5
6            39.9      20.5       11.4    98.0
9            34.1      11.1        5.9    97.9
12           57.3      37.5       23.1    99.4
25           63.9      60.5       43.4    99.8
26           53.2      25.6       14.9    91.6
average      50.7      28.0       17.3    96.8

accs: 96.9 & 96.9 & 90.4 & 91.7 & 94.6 & 93.5 & 96.9 & 92.8 & 94.2
F1_scores: 65.3 & 58.3 & 70.8 & 52.6 & 51.7 & 77.3 & 94.6 & 65.4 & 67.0
precisions: 73.1 & 69.1 & 65.7 & 47.7 & 41.2 & 70.1 & 92.5 & 56.9 & 64.5
recalls: 59.0 & 50.4 & 76.8 & 58.7 & 69.5 & 86.3 & 96.8 & 76.8 & 71.8
DISFA_AU_detection_threefold    CSN-IR50-stage4

         Accuracy  F1 score  Precision  Recall
AU
1            96.9      65.3       73.1    59.0
2            96.9      58.3       69.1    50.4
4            90.4      70.8       65.7    76.8
6            91.7      52.6       47.7    58.7
9            94.6      51.7       41.2    69.5
12           93.5      77.3       70.1    86.3
25           96.9      94.6       92.5    96.8
26           92.8      65.4       56.9    76.8
average      94.2      67.0       64.5    71.8

accs: 90.3 & 88.6 & 94.3 & 87.8 & 96.0 & 91.5 & 95.7 & 95.5 & 90.9 & 93.1 & 89.1 & 87.4 & 91.7
F1_scores: 71.0 & 63.1 & 84.0 & 63.7 & 85.9 & 51.0 & 84.5 & 64.7 & 58.8 & 49.6 & 74.3 & 56.9 & 67.3
precisions: 57.2 & 48.0 & 76.4 & 49.8 & 80.3 & 36.7 & 77.9 & 50.9 & 43.3 & 40.0 & 60.0 & 42.0 & 55.2
recalls: 93.5 & 92.2 & 93.3 & 88.1 & 92.3 & 83.8 & 92.3 & 88.8 & 91.2 & 65.2 & 97.5 & 88.2 & 88.9
DISFAPlus_AU_detection_ninefold    IR50

         Accuracy  F1 score  Precision  Recall
AU
1            90.3      71.0       57.2    93.5
2            88.6      63.1       48.0    92.2
4            94.3      84.0       76.4    93.3
5            87.8      63.7       49.8    88.1
6            96.0      85.9       80.3    92.3
9            91.5      51.0       36.7    83.8
12           95.7      84.5       77.9    92.3
15           95.5      64.7       50.9    88.8
17           90.9      58.8       43.3    91.2
20           93.1      49.6       40.0    65.2
25           89.1      74.3       60.0    97.5
26           87.4      56.9       42.0    88.2
average      91.7      67.3       55.2    88.9

accs: 58.1 & 58.1 & 49.1 & 55.6 & 37.9 & 28.9 & 57.0 & 44.4 & 39.4 & 34.4 & 54.2 & 51.8 & 47.4
F1_scores: 37.4 & 33.4 & 38.7 & 35.3 & 29.6 & 12.9 & 37.3 & 13.2 & 18.9 & 13.7 & 41.3 & 27.9 & 28.3
precisions: 23.1 & 20.1 & 24.0 & 21.5 & 17.4 & 6.9 & 23.0 & 7.1 & 10.4 & 7.4 & 26.1 & 16.2 & 16.9
recalls: 99.5 & 99.7 & 99.9 & 99.7 & 100.0 & 99.9 & 99.9 & 91.3 & 99.7 & 100.0 & 99.9 & 99.3 & 99.1
DISFAPlus_AU_detection_ninefold    IR50    One-Frame Calibration with Baseline Subtraction

         Accuracy  F1 score  Precision  Recall
AU
1            58.1      37.4       23.1    99.5
2            58.1      33.4       20.1    99.7
4            49.1      38.7       24.0    99.9
5            55.6      35.3       21.5    99.7
6            37.9      29.6       17.4   100.0
9            28.9      12.9        6.9    99.9
12           57.0      37.3       23.0    99.9
15           44.4      13.2        7.1    91.3
17           39.4      18.9       10.4    99.7
20           34.4      13.7        7.4   100.0
25           54.2      41.3       26.1    99.9
26           51.8      27.9       16.2    99.3
average      47.4      28.3       16.9    99.1

accs: 96.5 & 96.3 & 95.8 & 94.6 & 96.1 & 98.6 & 97.1 & 97.4 & 96.3 & 93.9 & 98.4 & 93.8 & 96.2
F1_scores: 86.8 & 84.0 & 87.0 & 79.5 & 86.0 & 86.4 & 89.2 & 70.1 & 73.3 & 35.5 & 95.0 & 70.9 & 78.6
precisions: 81.6 & 77.4 & 86.5 & 74.3 & 80.7 & 87.0 & 86.8 & 75.2 & 75.2 & 39.1 & 96.0 & 63.1 & 76.9
recalls: 92.8 & 91.7 & 87.5 & 85.5 & 92.1 & 85.9 & 91.6 & 65.6 & 71.5 & 32.4 & 93.9 & 80.9 & 80.9
DISFAPlus_AU_detection_ninefold    CSN-IR50-stage4

         Accuracy  F1 score  Precision  Recall
AU
1            96.5      86.8       81.6    92.8
2            96.3      84.0       77.4    91.7
4            95.8      87.0       86.5    87.5
5            94.6      79.5       74.3    85.5
6            96.1      86.0       80.7    92.1
9            98.6      86.4       87.0    85.9
12           97.1      89.2       86.8    91.6
15           97.4      70.1       75.2    65.6
17           96.3      73.3       75.2    71.5
20           93.9      35.5       39.1    32.4
25           98.4      95.0       96.0    93.9
26           93.8      70.9       63.1    80.9
average      96.2      78.6       76.9    80.9

accs: 96.5 & 90.1 & 95.8 & 95.9 & 95.4 & 88.3 & 94.8 & 86.7 & 92.7 & 96.5 & 93.3
F1_scores: 17.2 & 47.1 & 39.8 & 19.2 & 15.4 & 48.6 & 2.9 & 20.0 & 16.3 & 32.3 & 25.9
precisions: 15.2 & 40.4 & 49.2 & 11.1 & 8.9 & 42.6 & 1.7 & 12.6 & 13.5 & 26.5 & 22.2
recalls: 20.0 & 56.6 & 33.4 & 71.8 & 57.9 & 56.4 & 8.8 & 49.2 & 20.8 & 41.3 & 41.6
UNBCMcMaster_AU_detection_fivefold    IR50

         Accuracy  F1 score  Precision  Recall
AU
4            96.5      17.2       15.2    20.0
6            90.1      47.1       40.4    56.6
7            95.8      39.8       49.2    33.4
9            95.9      19.2       11.1    71.8
10           95.4      15.4        8.9    57.9
12           88.3      48.6       42.6    56.4
20           94.8       2.9        1.7     8.8
25           86.7      20.0       12.6    49.2
26           92.7      16.3       13.5    20.8
43           96.5      32.3       26.5    41.3
average      93.3      25.9       22.2    41.6

accs: 29.9 & 40.8 & 35.8 & 29.6 & 31.6 & 46.3 & 39.7 & 38.9 & 35.0 & 33.4 & 36.1
F1_scores: 4.0 & 20.6 & 11.4 & 1.9 & 2.1 & 25.8 & 2.8 & 9.3 & 8.7 & 5.1 & 9.2
precisions: 2.1 & 11.5 & 6.0 & 1.0 & 1.1 & 14.9 & 1.4 & 4.9 & 4.6 & 2.6 & 5.0
recalls: 81.5 & 98.2 & 99.7 & 100.0 & 100.0 & 95.3 & 99.8 & 92.7 & 90.1 & 90.0 & 94.7
UNBCMcMaster_AU_detection_fivefold    IR50    One-Frame Calibration with Baseline Subtraction

         Accuracy  F1 score  Precision  Recall
AU
4            29.9       4.0        2.1    81.5
6            40.8      20.6       11.5    98.2
7            35.8      11.4        6.0    99.7
9            29.6       1.9        1.0   100.0
10           31.6       2.1        1.1   100.0
12           46.3      25.8       14.9    95.3
20           39.7       2.8        1.4    99.8
25           38.9       9.3        4.9    92.7
26           35.0       8.7        4.6    90.1
43           33.4       5.1        2.6    90.0
average      36.1       9.2        5.0    94.7

accs: 98.1 & 92.9 & 95.5 & 97.3 & 97.8 & 92.4 & 97.0 & 94.7 & 96.1 & 96.7 & 95.9
F1_scores: 36.4 & 56.1 & 39.3 & 22.9 & 24.5 & 62.1 & 5.5 & 39.1 & 26.9 & 29.0 & 34.2
precisions: 44.7 & 54.1 & 44.6 & 14.2 & 16.4 & 60.9 & 3.8 & 32.2 & 38.2 & 25.6 & 33.5
recalls: 30.6 & 58.3 & 35.2 & 58.5 & 48.6 & 63.5 & 10.2 & 49.9 & 20.8 & 33.4 & 40.9
UNBCMcMaster_AU_detection_fivefold    CSN-IR50-stage4

         Accuracy  F1 score  Precision  Recall
AU
4            98.1      36.4       44.7    30.6
6            92.9      56.1       54.1    58.3
7            95.5      39.3       44.6    35.2
9            97.3      22.9       14.2    58.5
10           97.8      24.5       16.4    48.6
12           92.4      62.1       60.9    63.5
20           97.0       5.5        3.8    10.2
25           94.7      39.1       32.2    49.9
26           96.1      26.9       38.2    20.8
43           96.7      29.0       25.6    33.4
average      95.9      34.2       33.5    40.9

PCCs: .61 & .57 & .76 & .60 & .67 & .62 & .84 & .26 & .48 & .32 & .92 & .71 & .61
acrossICCs: .61 & .57 & .76 & .60 & .66 & .61 & .84 & .26 & .48 & .32 & .92 & .71 & .61
withinICCs: .34 & .34 & .63 & .31 & .55 & .42 & .85 & .21 & .42 & .22 & .91 & .58 & .48
MAEs: .34 & .31 & .48 & .13 & .31 & .23 & .36 & .24 & .35 & .23 & .33 & .41 & .31
MSEs: .38 & .36 & .62 & .07 & .31 & .21 & .31 & .22 & .33 & .19 & .27 & .36 & .30
DISFA_AU_intensity_estimation_threefold    CSN-IR50-stage1

,PCC,"across-participant ICC(3,1)","within-participant ICC(3,1)",MAE,MSE
AU,,,,,
1,0.61,0.61,0.34,0.34,0.38
2,0.57,0.57,0.34,0.31,0.36
4,0.76,0.76,0.63,0.48,0.62
5,0.60,0.60,0.31,0.13,0.07
6,0.67,0.66,0.55,0.31,0.31
9,0.62,0.61,0.42,0.23,0.21
12,0.84,0.84,0.85,0.36,0.31
15,0.26,0.26,0.21,0.24,0.22
17,0.48,0.48,0.42,0.35,0.33
20,0.32,0.32,0.22,0.23,0.19
25,0.92,0.92,0.91,0.33,0.27
26,0.71,0.71,0.58,0.41,0.36
average,0.61,0.61,0.48,0.31,0.30

PCCs: .66 & .69 & .77 & .61 & .62 & .60 & .84 & .32 & .51 & .33 & .95 & .78 & .64
acrossICCs: .66 & .69 & .77 & .59 & .60 & .58 & .83 & .32 & .51 & .32 & .94 & .77 & .63
withinICCs: .41 & .40 & .66 & .31 & .52 & .42 & .84 & .24 & .45 & .24 & .93 & .65 & .50
MAEs: .32 & .27 & .45 & .14 & .32 & .22 & .35 & .21 & .34 & .20 & .28 & .34 & .29
MSEs: .39 & .26 & .62 & .09 & .33 & .22 & .31 & .18 & .29 & .17 & .18 & .26 & .28
DISFA_AU_intensity_estimation_threefold    CSN-IR50-stage2

,PCC,"across-participant ICC(3,1)","within-participant ICC(3,1)",MAE,MSE
AU,,,,,
1,0.66,0.66,0.41,0.32,0.39
2,0.69,0.69,0.40,0.27,0.26
4,0.77,0.77,0.66,0.45,0.62
5,0.61,0.59,0.31,0.14,0.09
6,0.62,0.60,0.52,0.32,0.33
9,0.60,0.58,0.42,0.22,0.22
12,0.84,0.83,0.84,0.35,0.31
15,0.32,0.32,0.24,0.21,0.18
17,0.51,0.51,0.45,0.34,0.29
20,0.33,0.32,0.24,0.20,0.17
25,0.95,0.94,0.93,0.28,0.18
26,0.78,0.77,0.65,0.34,0.26
average,0.64,0.63,0.50,0.29,0.28

PCCs: .68 & .68 & .81 & .68 & .64 & .60 & .85 & .37 & .56 & .40 & .95 & .75 & .66
acrossICCs: .68 & .68 & .81 & .67 & .64 & .59 & .85 & .36 & .55 & .38 & .95 & .74 & .66
withinICCs: .40 & .40 & .69 & .39 & .56 & .45 & .85 & .28 & .47 & .26 & .94 & .66 & .53
MAEs: .28 & .24 & .42 & .11 & .32 & .22 & .33 & .19 & .26 & .18 & .25 & .32 & .26
MSEs: .35 & .28 & .53 & .06 & .33 & .22 & .29 & .17 & .25 & .15 & .16 & .26 & .25
DISFA_AU_intensity_estimation_threefold    CSN-IR50-stage3

,PCC,"across-participant ICC(3,1)","within-participant ICC(3,1)",MAE,MSE
AU,,,,,
1,0.68,0.68,0.40,0.28,0.35
2,0.68,0.68,0.40,0.24,0.28
4,0.81,0.81,0.69,0.42,0.53
5,0.68,0.67,0.39,0.11,0.06
6,0.64,0.64,0.56,0.32,0.33
9,0.60,0.59,0.45,0.22,0.22
12,0.85,0.85,0.85,0.33,0.29
15,0.37,0.36,0.28,0.19,0.17
17,0.56,0.55,0.47,0.26,0.25
20,0.40,0.38,0.26,0.18,0.15
25,0.95,0.95,0.94,0.25,0.16
26,0.75,0.74,0.66,0.32,0.26
average,0.66,0.66,0.53,0.26,0.25

PCCs: .61 & .52 & .75 & .53 & .66 & .64 & .85 & .37 & .47 & .23 & .93 & .70 & .60
acrossICCs: .57 & .50 & .71 & .51 & .57 & .55 & .79 & .29 & .40 & .19 & .88 & .61 & .55
withinICCs: .38 & .34 & .62 & .35 & .51 & .44 & .76 & .22 & .39 & .20 & .88 & .54 & .47
MAEs: .28 & .30 & .44 & .13 & .31 & .20 & .34 & .17 & .28 & .17 & .41 & .33 & .28
MSEs: .35 & .38 & .56 & .06 & .31 & .19 & .32 & .14 & .28 & .16 & .37 & .31 & .29
DISFA_AU_intensity_estimation_threefold    CSN-IR50-fc

,PCC,"across-participant ICC(3,1)","within-participant ICC(3,1)",MAE,MSE
AU,,,,,
1,0.61,0.57,0.38,0.28,0.35
2,0.52,0.50,0.34,0.30,0.38
4,0.75,0.71,0.62,0.44,0.56
5,0.53,0.51,0.35,0.13,0.06
6,0.66,0.57,0.51,0.31,0.31
9,0.64,0.55,0.44,0.20,0.19
12,0.85,0.79,0.76,0.34,0.32
15,0.37,0.29,0.22,0.17,0.14
17,0.47,0.40,0.39,0.28,0.28
20,0.23,0.19,0.20,0.17,0.16
25,0.93,0.88,0.88,0.41,0.37
26,0.70,0.61,0.54,0.33,0.31
average,0.60,0.55,0.47,0.28,0.29

PCCs: .65 & .53 & .75 & .50 & .65 & .63 & .84 & .46 & .48 & .23 & .93 & .65 & .61
acrossICCs: .58 & .49 & .70 & .48 & .55 & .54 & .79 & .35 & .41 & .21 & .87 & .56 & .54
withinICCs: .37 & .33 & .62 & .34 & .50 & .43 & .76 & .22 & .39 & .19 & .87 & .52 & .46
MAEs: .28 & .29 & .43 & .12 & .30 & .20 & .37 & .16 & .29 & .19 & .42 & .34 & .28
MSEs: .33 & .37 & .57 & .06 & .32 & .20 & .33 & .12 & .28 & .17 & .41 & .35 & .29
DISFA_AU_intensity_estimation_threefold    CSN-IR50-output

,PCC,"across-participant ICC(3,1)","within-participant ICC(3,1)",MAE,MSE
AU,,,,,
1,0.65,0.58,0.37,0.28,0.33
2,0.53,0.49,0.33,0.29,0.37
4,0.75,0.70,0.62,0.43,0.57
5,0.50,0.48,0.34,0.12,0.06
6,0.65,0.55,0.50,0.30,0.32
9,0.63,0.54,0.43,0.20,0.20
12,0.84,0.79,0.76,0.37,0.33
15,0.46,0.35,0.22,0.16,0.12
17,0.48,0.41,0.39,0.29,0.28
20,0.23,0.21,0.19,0.19,0.17
25,0.93,0.87,0.87,0.42,0.41
26,0.65,0.56,0.52,0.34,0.35
average,0.61,0.54,0.46,0.28,0.29

accs: 93.2 & 92.7 & 88.2 & 90.4 & 93.1 & 92.3 & 94.8 & 91.5 & 92.0
F1_scores: 50.8 & 43.7 & 65.9 & 53.3 & 46.7 & 75.1 & 90.6 & 60.6 & 60.8
precisions: 39.8 & 32.8 & 58.7 & 43.4 & 34.5 & 64.4 & 90.3 & 51.2 & 51.9
recalls: 70.3 & 65.4 & 75.2 & 69.0 & 72.4 & 90.1 & 90.9 & 74.1 & 75.9
DISFA_AU_detection_threefold    CSN-IR50-stage1

         Accuracy  F1 score  Precision  Recall
AU
1            93.2      50.8       39.8    70.3
2            92.7      43.7       32.8    65.4
4            88.2      65.9       58.7    75.2
6            90.4      53.3       43.4    69.0
9            93.1      46.7       34.5    72.4
12           92.3      75.1       64.4    90.1
25           94.8      90.6       90.3    90.9
26           91.5      60.6       51.2    74.1
average      92.0      60.8       51.9    75.9

accs: 93.4 & 95.0 & 89.9 & 90.5 & 94.1 & 93.3 & 96.3 & 94.4 & 93.3
F1_scores: 54.0 & 54.7 & 70.5 & 52.3 & 48.4 & 77.2 & 93.4 & 71.5 & 65.2
precisions: 41.3 & 44.9 & 63.3 & 43.3 & 38.0 & 68.6 & 91.4 & 65.2 & 57.0
recalls: 78.0 & 70.0 & 79.5 & 65.9 & 66.6 & 88.4 & 95.4 & 79.3 & 77.9
DISFA_AU_detection_threefold    CSN-IR50-stage2

         Accuracy  F1 score  Precision  Recall
AU
1            93.4      54.0       41.3    78.0
2            95.0      54.7       44.9    70.0
4            89.9      70.5       63.3    79.5
6            90.5      52.3       43.3    65.9
9            94.1      48.4       38.0    66.6
12           93.3      77.2       68.6    88.4
25           96.3      93.4       91.4    95.4
26           94.4      71.5       65.2    79.3
average      93.3      65.2       57.0    77.9

accs: 92.3 & 93.7 & 90.7 & 90.2 & 90.6 & 92.4 & 96.3 & 93.4 & 92.5
F1_scores: 50.1 & 44.0 & 73.5 & 54.7 & 41.0 & 75.3 & 93.4 & 67.3 & 62.4
precisions: 37.0 & 35.6 & 65.0 & 43.1 & 27.8 & 64.8 & 92.8 & 59.6 & 53.2
recalls: 77.5 & 57.5 & 84.5 & 74.8 & 77.7 & 89.9 & 93.9 & 77.3 & 79.1
DISFA_AU_detection_threefold    CSN-IR50-stage3

         Accuracy  F1 score  Precision  Recall
AU
1            92.3      50.1       37.0    77.5
2            93.7      44.0       35.6    57.5
4            90.7      73.5       65.0    84.5
6            90.2      54.7       43.1    74.8
9            90.6      41.0       27.8    77.7
12           92.4      75.3       64.8    89.9
25           96.3      93.4       92.8    93.9
26           93.4      67.3       59.6    77.3
average      92.5      62.4       53.2    79.1

accs: 69.1 & 75.3 & 52.4 & 49.0 & 50.3 & 64.7 & 65.9 & 55.5 & 60.3
F1_scores: 21.7 & 18.6 & 38.8 & 23.2 & 14.0 & 42.0 & 61.9 & 27.1 & 30.9
precisions: 12.4 & 10.8 & 24.1 & 13.2 & 7.6 & 26.7 & 44.8 & 15.9 & 19.4
recalls: 86.2 & 65.3 & 99.0 & 97.4 & 96.8 & 99.1 & 99.9 & 94.0 & 92.2
DISFA_AU_detection_threefold    CSN-IR50-fc

         Accuracy  F1 score  Precision  Recall
AU
1            69.1      21.7       12.4    86.2
2            75.3      18.6       10.8    65.3
4            52.4      38.8       24.1    99.0
6            49.0      23.2       13.2    97.4
9            50.3      14.0        7.6    96.8
12           64.7      42.0       26.7    99.1
25           65.9      61.9       44.8    99.9
26           55.5      27.1       15.9    94.0
average      60.3      30.9       19.4    92.2

accs: 62.6 & 74.4 & 53.3 & 48.4 & 49.0 & 62.8 & 63.9 & 53.6 & 58.5
F1_scores: 18.8 & 17.8 & 39.1 & 23.0 & 13.5 & 40.7 & 60.5 & 25.8 & 29.9
precisions: 10.5 & 10.3 & 24.4 & 13.0 & 7.3 & 25.6 & 43.4 & 15.0 & 18.7
recalls: 86.9 & 64.3 & 98.5 & 97.7 & 95.5 & 99.3 & 99.9 & 91.6 & 91.7
DISFA_AU_detection_threefold    CSN-IR50-output

         Accuracy  F1 score  Precision  Recall
AU
1            62.6      18.8       10.5    86.9
2            74.4      17.8       10.3    64.3
4            53.3      39.1       24.4    98.5
6            48.4      23.0       13.0    97.7
9            49.0      13.5        7.3    95.5
12           62.8      40.7       25.6    99.3
25           63.9      60.5       43.4    99.9
26           53.6      25.8       15.0    91.6
average      58.5      29.9       18.7    91.7